# Generated by Django 4.1.7 on 2023-02-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkashAPI", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="agreement",
            new_name="agreementModel",
        ),
        migrations.RenameModel(
            old_name="createPaymentID",
            new_name="createPaymentIDModel",
        ),
        migrations.RenameModel(
            old_name="successPayment",
            new_name="grantTokenModel",
        ),
        migrations.RenameModel(
            old_name="grantToken",
            new_name="successPaymentModel",
        ),
        migrations.RenameField(
            model_name="granttokenmodel",
            old_name="paymentID",
            new_name="refreshToken",
        ),
        migrations.RenameField(
            model_name="granttokenmodel",
            old_name="trxID",
            new_name="token",
        ),
        migrations.RenameField(
            model_name="successpaymentmodel",
            old_name="refreshToken",
            new_name="paymentID",
        ),
        migrations.RenameField(
            model_name="successpaymentmodel",
            old_name="token",
            new_name="trxID",
        ),
    ]
