# Generated by Django 4.1.7 on 2023-02-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bkashAPI", "0002_rename_agreement_agreementmodel_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="granttokenmodel",
            old_name="refreshToken",
            new_name="id_token",
        ),
        migrations.RenameField(
            model_name="granttokenmodel",
            old_name="token",
            new_name="refresh_token",
        ),
    ]
