# Generated by Django 4.1.7 on 2023-02-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bkashAPI", "0004_refundmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreementmodel",
            name="customerMsisdn",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
